const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  apis: ['./routes/restaurant.js', './routes/user.js'],
  basePath: '/',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Restaurant API',
      version: '1.0.0'
    }
  }
};
const specs = swaggerJsdoc(options);
export default specs;
